package org.firstinspires.ftc.teamcode.kotlinKit.auxiliary

enum class KeyBind {
    DPAD_UP_1, DPAD_DOWN_1, DPAD_LEFT_1, DPAD_RIGHT_1,
    CIRCLE_1, CROSS_1, SQUARE_1, TRIANGLE_1,
    A_1, B_1, X_1, Y_1,
    LEFT_BUMPER_1, RIGHT_BUMPER_1,
    OPTIONS_1, SHARE_1, PS_1, TOUCHPAD_1,
    LEFT_STICK_BUTTON_1, RIGHT_STICK_BUTTON_1,

    DPAD_UP_2, DPAD_DOWN_2, DPAD_LEFT_2, DPAD_RIGHT_2,
    CIRCLE_2, CROSS_2, SQUARE_2, TRIANGLE_2,
    A_2, B_2, X_2, Y_2,
    LEFT_BUMPER_2, RIGHT_BUMPER_2,
    OPTIONS_2, SHARE_2, PS_2, TOUCHPAD_2,
    LEFT_STICK_BUTTON_2, RIGHT_STICK_BUTTON_2;
}